"""defined model

Revision ID: 8fe80d5caf20
Revises: 
Create Date: 2018-04-17 15:41:58.807643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fe80d5caf20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carparks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('num_of_space', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('longtitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('demand', sa.String(length=64), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), nullable=False),
    sa.Column('last_updated_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_timestamp', sa.DateTime(), nullable=False),
    sa.Column('exit_timestamp', sa.DateTime(), nullable=False),
    sa.Column('tx_timestamp', sa.DateTime(), nullable=False),
    sa.Column('parker_type', sa.String(length=64), nullable=False),
    sa.Column('license', sa.String(length=64), nullable=True),
    sa.Column('gross_price', sa.Float(), nullable=True),
    sa.Column('validation', sa.Float(), nullable=True),
    sa.Column('validation_type', sa.String(length=64), nullable=True),
    sa.Column('net_price', sa.Float(), nullable=True),
    sa.Column('payment_method', sa.String(length=64), nullable=True),
    sa.Column('payment_location', sa.String(length=64), nullable=True),
    sa.Column('entry_gate', sa.String(length=64), nullable=True),
    sa.Column('exit_gate', sa.String(length=64), nullable=True),
    sa.Column('operator', sa.String(length=64), nullable=True),
    sa.Column('length_of_stay', sa.Float(), nullable=False),
    sa.Column('length_of_stay_until_pay', sa.Float(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), nullable=False),
    sa.Column('last_updated_timestamp', sa.DateTime(), nullable=False),
    sa.Column('carpark_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carpark_id'], ['carparks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('carparks')
    # ### end Alembic commands ###
